# This formula is auto-generated by GoReleaser on each release.
# To install via the tap, use: brew install PhilipKram/tap/jenkins-cli
# This file serves as a reference template.

class JenkinsCli < Formula
  desc "A CLI tool for controlling Jenkins from the terminal"
  homepage "https://github.com/PhilipKram/Jenkins-CLI"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v#{version}/jenkins-cli_#{version}_darwin_amd64.tar.gz"
    end

    on_arm do
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v#{version}/jenkins-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v#{version}/jenkins-cli_#{version}_linux_amd64.tar.gz"
    end

    on_arm do
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v#{version}/jenkins-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  def install
    bin.install "jenkins-cli"
  end

  test do
    system "#{bin}/jenkins-cli", "--version"
  end
end
